# Generated by Django 6.0.2 on 2026-02-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Vehicle',
            new_name='vehicle',
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.IntegerField(),
        ),
    ]
