# Generated by Django 6.0.2 on 2026-02-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_vehicle_booking_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(max_length=10),
        ),
    ]
